<?php

  function contenido () {
    $datos = array();

    $datos[0] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/Doctor_muerte.jpg"."||"."Doctor Muerte "."||"."El Doctor Muerte (Doctor Doom) es posiblemente el mayor villano de Marvel Comics. El archienemigo de los 4 Fantásticos ha sido un dolor de cabeza para prácticamente cualquier héroe o grupo de héroes alguna vez a lo largo de los últimos 70 años. Desde Los Vengadores hasta Spider-man o Luke Cage, es raro que no haya un solo héroe que se haya enfrentado a él en alguna ocasión.";
    $datos[1] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/duende_verde.jpg"."||"."Duende Verde"."||"."Norman Osborn, nombre real del villano conocido como el Duende Verde, es el gran enemigo de Spider-man. Se trata de un industrial dueño de Oscorp, una empresa armamentística puntera, que sufre un trastorno serio de personalidad múltiple y esquizonfrenia debido un suero experimental que mejoraba las habilidades físicas de quien lo ingiriera. Sin embargo, los efectos secundarios del suero le llevaron a convertirse en un criminal con un traje y un arsenal temáticos de Halloween. Su carrera delictiva le hizo enfrentarse a Spider-man, quien más tarde descubriría que era Peter Parker, el amigo de su hijo Harry.  ";
    $datos[2] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/kingpin.jpg"."||"."Kingpin"."||"."Originalmente concebido como villano de Spider-man, el señor del crimen de Nueva York acabó convirtiéndose en némesis de Daredevil durante la etapa de Frank Miller en los cómics del Hombre Sin Miedo. Pero que su orondo aspecto no os engañe. Si bien Wilson Fisk (nombre real del personaje) está 'fuertecito' realmente todo eso es músculo. Su resistencia natural y su entrenamiento físico cuerpo a cuerpo le convierten en un enemigo letal en las distancias cortas. A las largas... digamos que su imperio criminal sabe cómo hacer desaparecer gente que le molesta.";
    $datos[3] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/loki.jpg"."||"."Loki"."||"."El dios nórdico de las Mentiras y el Engaño. Y el hermano adoptivo de Thor según la mitología de Marvel y también su mayor rival clásico. Loki es un medio gigante de hielo criado en Asgard. Debido a su ascendencia, siempre fue tratado con desdén por los asgardianos, a pesar de ser criado como hijo de Odín y hermano de Thor. Esto creó un gran resentimiento en el joven Loki, lo cual le hizo tratar de humillar a Thor una y otra vez, para ganar el favor de su 'padre' y así poder ser alguna vez su heredero. Sobra decir que fracasó y acabó falleciendo en los eventos de Asedio.";
    $datos[4] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/magneto.jpg"."||"."Magneto"."||"."El villano/aliado recurrente de la Patrulla-X no podía faltar en esta lista. Se trata de un mutante capaz de controlar los campos magnéticos, pudiendo manipular el metal con su mente. Suele entrar en conflicto con los héroes de Marvel debido su ideología supremacista, que propugna suplantar a la especie humana en favor de la población mutante. Debido a esto, durante décadas Magneto fue una de las bestias negras de los héroes de Marvel Comics, aunque sus némesis habituales fueran los X-men. El guionista Chris Claremont cambió todo esto y presentó a Magneto como un anti-héroe, víctima del Holocausto, que llegó a luchar codo con codo con los buenos durante las Secret Wars.";
    $datos[5] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/Thanos.jpg"."||"."Thanos"."||"."Su nombre significa muerte. Literalmente. Es un ser aliénigena, nacido en la sociedad de los Eternos de TItán, una de las lunas de Saturno. Debido a haber nacido con genes desviantes (una facción de los eternos, dotada de ciertos poderes y malformaciones), Thanos creció como un paria. Encontró solaz en la compañía de la entidad conocida como Muerte, de la cual cayó rendido y enamorado locamente. Tratando de ganar su afecto, Thanos comenzó una campaña para acabar con la vida del Universo que dio lugar a su enfrentamiento con los héroes una y otra vez. En los últimos años, tras haber protagonizado varias novelas gráficas, regresó al Universo Marvel al inicio de la Civil War 2, siendo una parte implicada en su detonación.";
    $datos[6] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/Ultron.jpg"."||"."Ultron"."||"."Uno de los enemigos de Los Vengadores que peor se lo ha hecho pasar al grupo y al Universo Marvel en general, como ya demostró en la novela gráfica Rage of Ultrón y el crossover Age of Ultron. Ultrón es un robot creado por Hank Pym, el Hombre Hormiga original, quien estaba coqueteando con la creación inteligencia artificial. Ultron es el hijo artificial de Pym, creado a partir de sus patrones mentales. Sin embargo, el androide sufre con una especie de complejo de Edipo, por el cual busca eliminar a su creador (y de paso a la especie humana).";
    $datos[7] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/Annihilus.jpg"."||"."Ultron"."||"."Este alienígena insectoíde es el Señor de la Zona Negativa, un universo de Anti-Materia opuesto al nuestro, en donde gobierna gracias a un báculo que le permite subyugar a la población. Gracias al uso de la tecnología y a una no poco usual biología,Annihilus es esencialmente un ser inmortal, capaz de renacer una y otra vez mientras las reinas de su ejército sigan con vida. Entre sus grandes logros se encuentran el de haber diezmado media galaxia, a los Nova Corps y lograr que los imperios Kree y Skrull se aliaran entre sí para detenerle.";
    $datos[8] = "../../../php/Gradder_y_PHP/raw/imagenesEstiloGoogle/img/cap.jpg"."||"."Ultron"."||"."Hemos dejado el último puesto para el que hasta hace poco era uno de los mayores héroes de Marvel, un ejemplo de virtud y un dechado de bondad. Sin embargo, la nueva etapa en los cómics ha revelado que el Capitán América es en realidad un agente durmiente de HYDRA. Esto, se ha explicado, ocurre porque un objeto llamado el Cubo Cósmico toma conciencia de sí mismo y es manipulado por Cráneo Rojo para alterar la realidad y la historia, reescribiendo el pasado por completo, convirtiendo a Steve Rogers en un leal agente filonazi.";

    return $datos;
  }

?>